[book]
title = "Swift && SwiftUI"
authors = ["Tuấn Em"]
description = "Học Swift và SwiftUI bằng niềm đam mê"
language = "vi"

[output.html]
git-repository-url = "https://github.com/tuanemdev/swift-book"

[output.html.fold]
enable = true

[output.html.code.hidelines]
swift = "#"

[preprocessor.katex]
after = ["links"]
